"""Auto migration

Revision ID: 1f8bd8649f8f
Revises: a5cf28ff4c3e
Create Date: 2024-07-16 20:58:16.522582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f8bd8649f8f'
down_revision: Union[str, None] = 'a5cf28ff4c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
