"""empty message

Revision ID: 86e301c432c1
Revises: b827dcfd469d
Create Date: 2024-07-18 16:19:26.693839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e301c432c1'
down_revision: Union[str, None] = 'b827dcfd469d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_users_company', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_country', table_name='users')
    op.create_index(op.f('ix_users_country'), 'users', ['country'], unique=True)
    op.drop_column('users', 'email')
    op.drop_column('users', 'username')
    op.drop_column('users', 'company')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_country'), table_name='users')
    op.create_index('ix_users_country', 'users', ['country'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_company', 'users', ['company'], unique=False)
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
