"""empty message

Revision ID: e1a9d23b7899
Revises: 86e301c432c1
Create Date: 2024-07-18 16:27:07.182747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a9d23b7899'
down_revision: Union[str, None] = '86e301c432c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
