"""empty message

Revision ID: edb66062db95
Revises: b7c36963b79c
Create Date: 2024-07-16 20:28:27.847446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edb66062db95'
down_revision: Union[str, None] = 'b7c36963b79c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_country'), 'users', ['country'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_country'), table_name='users')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
